"""create initial database schema

Revision ID: e80ba9924114
Revises: 
Create Date: 2026-09-29 16:38:54.413067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e80ba9924114'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('reorder_level', sa.Integer(), nullable=False,server_default="0",),)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'reorder_level')
    # ### end Alembic commands ###
